spring:
  application:
    name: eureka-discovery-service

server:
  port: 24499
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${erukaserver:http://localhost:24499/eureka}
