spring:
  application:
    name: service-2
  webflux:
    base-path: /service2
    
server:
  port: 24502
  servlet:
    contextPath: /service2
  
eureka:
  client:
    service-url:
      defaultZone: ${erukaserver:http://localhost:24499/eureka}
