spring:
  application:
    name: service-1
  webflux:
    base-path: /service1
    
server:
  port: 24501
  servlet:
    contextPath: /service1
  
eureka:
  client:
    service-url:
      defaultZone: ${erukaserver:http://localhost:24499/eureka}
